# Generated by Django 5.2.4 on 2025-07-18 06:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_universities'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
