# Generated by Django 5.2.4 on 2025-07-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_group_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
