# Generated by Django 5.2.4 on 2025-07-20 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_note_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='vote',
        ),
        migrations.AddField(
            model_name='note',
            name='Downvote',
            field=models.ManyToManyField(related_name='Downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='Upvote',
            field=models.ManyToManyField(related_name='Upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
